#!/bin/bash

## hyphop ##

#= khadas vims - fan control via user mode i2c
#/

#s https://github.com/hyphop/khadas-utils
#l https://github.com/hyphop/khadas-utils/blob/master/utils/fan
#d https://raw.githubusercontent.com/hyphop/khadas-utils/master/utils/fan

HELP(){ echo "khadas vims - fan control \
USAGE
    fan [0|1|2|3|min|mid|max|on|off] [--help]


";}

A=0x18
C=0x88
B=
b=

CMD(){
    echo "[#] $@">&2
    $@
}

which i2cget 1>/dev/null 2>/dev/null || {
    echo "[e] need install i2c-tools // apt-get install i2c-tools">&2
    exit 1
}

OK=
# check i2c bus
for B in /dev/i2c-?; do
    [ -c $B ] || {
	echo "[e] i2c devs not found">&2
	exit 1
    }
    b=${B#*-}
    i2cget -y -f $b $A 1>/dev/null && {
	OK=1
    	break
    }
done

[ "$OK" ] || {
    echo "[i] i2c device not found by $A $C">&2
    exit 1
}

#echo "[i] b $B $b ">&2

GET(){
    echo $(i2cget -y $b $A $C b 2>/dev/null)
}


SET(){
    CMD i2cset -y $b $A $C $1 b
    echo "[i] set FUN SPEED: $1">&2
}

DEFAULT=1

#echo "[i] $(GET)">&2

[ "$1" ] || {
    HELP
    exit 1
}

for a in $@; do
case $a in
    on|e*)
    SET $DEFAULT
    ;;
    1|2|3)
    SET $a
    ;;
    lo*)
    SET 1
    ;;
    mi*)
    SET 2
    ;;
    ma*)
    SET 3
    ;;
    of*|0|d*)
    SET 0
    ;;
    *)
    HELP
esac
done

